//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LabSampleManager.Desktop.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LabSampleManager.Desktop.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to icon-lab-sample-manager.
        /// </summary>
        public static string ApplicationIconAccessibleName {
            get {
                return ResourceManager.GetString("ApplicationIconAccessibleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lab Sample Manager.
        /// </summary>
        public static string ApplicationName {
            get {
                return ResourceManager.GetString("ApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to icon-dashboard.
        /// </summary>
        public static string DashboardIconAccessibleName {
            get {
                return ResourceManager.GetString("DashboardIconAccessibleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Laboratory Overview.
        /// </summary>
        public static string DashboardSubtitle {
            get {
                return ResourceManager.GetString("DashboardSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        public static string DashboardTitle {
            get {
                return ResourceManager.GetString("DashboardTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doing now what patients needs next.
        /// </summary>
        public static string FooterTagline {
            get {
                return ResourceManager.GetString("FooterTagline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        public static string MenuDashboard {
            get {
                return ResourceManager.GetString("MenuDashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing.
        /// </summary>
        public static string MenuProcessing {
            get {
                return ResourceManager.GetString("MenuProcessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register Sample.
        /// </summary>
        public static string MenuRegisterSample {
            get {
                return ResourceManager.GetString("MenuRegisterSample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Samples.
        /// </summary>
        public static string MenuSamples {
            get {
                return ResourceManager.GetString("MenuSamples", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation.
        /// </summary>
        public static string MenuValidation {
            get {
                return ResourceManager.GetString("MenuValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to icon-processing.
        /// </summary>
        public static string ProcessingIconAccessibleName {
            get {
                return ResourceManager.GetString("ProcessingIconAccessibleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Track analyzer workloads and sample execution.
        /// </summary>
        public static string ProcessingMonitorSubtitle {
            get {
                return ResourceManager.GetString("ProcessingMonitorSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing Monitor.
        /// </summary>
        public static string ProcessingMonitorTitle {
            get {
                return ResourceManager.GetString("ProcessingMonitorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to icon-register-sample.
        /// </summary>
        public static string RegisterSampleIconAccessibleName {
            get {
                return ResourceManager.GetString("RegisterSampleIconAccessibleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new laboratory sample request.
        /// </summary>
        public static string RegisterSampleSubtitle {
            get {
                return ResourceManager.GetString("RegisterSampleSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register Sample.
        /// </summary>
        public static string RegisterSampleTitle {
            get {
                return ResourceManager.GetString("RegisterSampleTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string CancelAction {
            get {
                return ResourceManager.GetString("CancelAction", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Enter the basic details for the new sample.
        /// </summary>
        public static string SampleInformationSubtitle {
            get {
                return ResourceManager.GetString("SampleInformationSubtitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Sample Information.
        /// </summary>
        public static string SampleInformationTitle {
            get {
                return ResourceManager.GetString("SampleInformationTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Select the tests to be perfomed on this sample.
        /// </summary>
        public static string RequestedTestsSubtitle {
            get {
                return ResourceManager.GetString("RequestedTestsSubtitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Requested Tests.
        /// </summary>
        public static string RequestedTestsTitle {
            get {
                return ResourceManager.GetString("RequestedTestsTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Please ensure the following.
        /// </summary>
        public static string RegistrationRulesSubtitle {
            get {
                return ResourceManager.GetString("RegistrationRulesSubtitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Registration Rules.
        /// </summary>
        public static string RegistrationRulesTitle {
            get {
                return ResourceManager.GetString("RegistrationRulesTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Register Sample.
        /// </summary>
        public static string RegisterSampleAction {
            get {
                return ResourceManager.GetString("RegisterSampleAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validate and review completed results.
        /// </summary>
        public static string ResultsValidationSubtitle {
            get {
                return ResourceManager.GetString("ResultsValidationSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Results Validation.
        /// </summary>
        public static string ResultsValidationTitle {
            get {
                return ResourceManager.GetString("ResultsValidationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to logo-roche.
        /// </summary>
        public static string RocheLogoAccessibleName {
            get {
                return ResourceManager.GetString("RocheLogoAccessibleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to icon-samples.
        /// </summary>
        public static string SamplesIconAccessibleName {
            get {
                return ResourceManager.GetString("SamplesIconAccessibleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search and manage laboratory samples.
        /// </summary>
        public static string SamplesSubtitle {
            get {
                return ResourceManager.GetString("SamplesSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Samples.
        /// </summary>
        public static string SamplesTitle {
            get {
                return ResourceManager.GetString("SamplesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Barcode.
        /// </summary>
        public static string BarcodeLabel { get { return ResourceManager.GetString("BarcodeLabel", resourceCulture); } }

        /// <summary>
        ///   Looks up a localized string similar to Patient Code.
        /// </summary>
        public static string PatientCodeLabel { get { return ResourceManager.GetString("PatientCodeLabel", resourceCulture); } }

        /// <summary>
        ///   Looks up a localized string similar to Sample Type.
        /// </summary>
        public static string SampleTypeLabel { get { return ResourceManager.GetString("SampleTypeLabel", resourceCulture); } }

        /// <summary>
        ///   Looks up a localized string similar to Select the sample type.
        /// </summary>
        public static string SampleTypeSubtitle { get { return ResourceManager.GetString("SampleTypeSubtitle", resourceCulture); } }

        /// <summary>
        ///   Looks up a localized string similar to Blood.
        /// </summary>
        public static string SampleTypeBlood { get { return ResourceManager.GetString("SampleTypeBlood", resourceCulture); } }

        /// <summary>
        ///   Looks up a localized string similar to Urine.
        /// </summary>
        public static string SampleTypeUrine { get { return ResourceManager.GetString("SampleTypeUrine", resourceCulture); } }

        /// <summary>
        ///   Looks up a localized string similar to Priority.
        /// </summary>
        public static string PriorityLabel { get { return ResourceManager.GetString("PriorityLabel", resourceCulture); } }

        /// <summary>
        ///   Looks up a localized string similar to Normal.
        /// </summary>
        public static string PriorityNormal { get { return ResourceManager.GetString("PriorityNormal", resourceCulture); } }

        /// <summary>
        ///   Looks up a localized string similar to Urgent.
        /// </summary>
        public static string PriorityUrgent { get { return ResourceManager.GetString("PriorityUrgent", resourceCulture); } }

        /// <summary>
        ///   Looks up a localized string similar to STAT.
        /// </summary>
        public static string PriorityStat { get { return ResourceManager.GetString("PriorityStat", resourceCulture); } }

        /// <summary>
        ///   Looks up a localized string similar to Received Date & Time.
        /// </summary>
        public static string ReceivedDateTimeLabel { get { return ResourceManager.GetString("ReceivedDateTimeLabel", resourceCulture); } }

        /// <summary>
        ///   Looks up a localized string similar to Date and time the sample was received in the laboratory.
        /// </summary>
        public static string ReceivedDateTimeSubtitle { get { return ResourceManager.GetString("ReceivedDateTimeSubtitle", resourceCulture); } }

        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        public static string NotesLabel { get { return ResourceManager.GetString("NotesLabel", resourceCulture); } }

        /// <summary>
        ///   Looks up a localized string similar to Enter any additional information (e.g., clinical details, special instructions).
        /// </summary>
        public static string NotesPlaceholder { get { return ResourceManager.GetString("NotesPlaceholder", resourceCulture); } }

        /// <summary>
        ///   Looks up a localized string similar to *.
        /// </summary>
        public static string RequiredFieldIndicator { get { return ResourceManager.GetString("RequiredFieldIndicator", resourceCulture); } }

        /// <summary>
        ///   Looks up a localized string similar to the dropdown indicator.
        /// </summary>
        public static string DropDownIndicator { get { return ResourceManager.GetString("DropDownIndicator", resourceCulture); } }

        public static string UnsupportedMenuDestination {
            get {
                return ResourceManager.GetString("UnsupportedMenuDestination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dr. Bruce Banner.
        /// </summary>
        public static string UserDisplayName {
            get {
                return ResourceManager.GetString("UserDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BB.
        /// </summary>
        public static string UserInitials {
            get {
                return ResourceManager.GetString("UserInitials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Laboratory Scientist.
        /// </summary>
        public static string UserRole {
            get {
                return ResourceManager.GetString("UserRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to icon-validation.
        /// </summary>
        public static string ValidationIconAccessibleName {
            get {
                return ResourceManager.GetString("ValidationIconAccessibleName", resourceCulture);
            }
        }
    }
}
